# Config file for Mario Kart 64 NTSC Recompilation.

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
#elf_path = "mk64.us.elf"
symbols_file_path = "MK64RecompSyms/mk64.us.syms.toml"
rom_file_path = "mk64.us.z64"

manual_funcs = [
    { name = "osWritebackDCacheAll_stub", section = ".main", vram = 0x800CD890, size = 0x30 },
    { name = "osInvalICache_stub", section = ".main", vram = 0x800CDB00, size = 0x80 },
    { name = "osGetCount_stub", section = ".main", vram = 0x800D11A0, size = 0x10 },
    { name = "tkmk_80040C54", section = ".main", vram = 0x80040C54, size = 0x3C },
]

[patches]
stubs = [
	"osWritebackDCacheAll_stub",
	"osInvalICache_stub",
	"osGetCount_stub",
]

ignored = [
	"__osPfsReleasePages",
	"__osBlockSum",
	"__osPfsDeclearPage",
]

[[patches.instruction]]
func = "tkmk_80040C54"
vram = 0x80040C8C
value = 0x00000000

[[patches.instruction]] #osInvalDCache
func = "func_802A8348"
vram = 0x802A8380
value = 0x00000000

[[patches.instruction]] #osInvalDCache
func = "func_802A841C"
vram = 0x802A8454
value = 0x00000000

[[patches.instruction]] #osInvalDCache
func = "func_802A80B0"
vram = 0x802A80D8
value = 0x00000000

[[patches.instruction]] #osPfsInit
func = "func_800AA2EC"
vram = 0x800AA43C
value = 0x00000000

[[patches.instruction]] #osPfsInit
func = "func_800B6014"
vram = 0x800B6050
value = 0x00000000

[[patches.instruction]] #osPfsInit
func = "controller_pak_1_status"
vram = 0x800B5C54
value = 0x00000000

[[patches.instruction]] #osPfsInit
func = "func_80091D74"
vram = 0x80091E14
value = 0x00000000

[[patches.instruction]]
func = "controller_pak_2_status" #osPfsInit
vram = 0x800B5E5C
value = 0x00000000

[[patches.instruction]] #osPfsInit
func = "func_8800B6AF8"
vram = 0x800B6B1C
value = 0x00000000

[[patches.instruction]] #osPfsInit
func = "func_800B5F30"
vram = 0x800B5F6C
value = 0x00000000

[[patches.instruction]] #osPfsIsPlug
func = "func_80091D74"
vram = 0x80091DF0
value = 0x00000000

[[patches.instruction]] #osPfsIsPlug
func = "check_for_controller_pak"
vram = 0x800B5B58
value = 0x00000000

[[patches.instruction]]
func = "debug_print_ghost_kart_character_id" #rmonPrintf
vram = 0x800B4588
value = 0x00000000

[[patches.instruction]]
func = "debug_print_ghost_kart_character_id" #rmonPrintf
vram = 0x800B45A8
value = 0x00000000

[[patches.instruction]]
func = "debug_print_ghost_kart_character_id" #rmonPrintf
vram = 0x800B45C8
value = 0x00000000

[[patches.instruction]] #rmonPrintf
func = "func_80095BD0"
vram = 0x80095C24
value = 0x00000000

[[patches.instruction]] #rmonPrintf
func = "func_80095BD0"
vram = 0x80095C38
value = 0x00000000
