# Config file for Mario Kart 64 NTSC Recompilation.

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
symbols_file_path = "MK64RecompSyms/mk64.us.syms.toml"
rom_file_path = "mk64.us.z64"

[patches]
stubs = [
	"osInvalDCache_recomp",
	"osInvalICache_recomp",
	"osWritebackDCacheAll_recomp",
	"osGetCount_recomp",
	"osPfsInit_recomp",
	"osPfsIsPlug_recomp",
	"__osPfsSelectBank_recomp",
	"__osContRamRead_recomp",
	"__osContRamWrite_recomp",
	"rmonPrintf_recomp",
]