# Config file for Majora's Mask NTSC 1.0 Recompilation.

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
elf_path = "mk64.us.elf"
rom_file_path = "mk64.us.z64"